"""fix wrong relationship RefreshToken model for api_auth

Revision ID: 73f66cb8617e
Revises: ba5f671dc88c
Create Date: 2025-12-26 20:54:09.730603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73f66cb8617e'
down_revision: Union[str, Sequence[str], None] = 'ba5f671dc88c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
