"""add salary and source fields to vacancy model

Revision ID: bbd0f91a67b5
Revises: f2e6f9373e0d
Create Date: 2025-11-22 21:32:11.871906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bbd0f91a67b5"
down_revision: Union[str, Sequence[str], None] = "f2e6f9373e0d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("vacancies", sa.Column("salary", sa.JSON(), nullable=True))
    op.add_column("vacancies", sa.Column("source", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("vacancies", "source")
    op.drop_column("vacancies", "salary")
    # ### end Alembic commands ###
