"""add new field active_resume_id

Revision ID: f2e6f9373e0d
Revises: 66acaf745014
Create Date: 2025-11-15 19:07:09.703238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f2e6f9373e0d"
down_revision: Union[str, Sequence[str], None] = "66acaf745014"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("active_resume_id", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "active_resume_id")
    # ### end Alembic commands ###
